Fb entrance page integration
RGLab/LabKeyModules pull request #115
Opened 2021-04-23 19:58 UTC by guoz24

## Description

## Related PRs

## Notion Ticket

## PR Checklist for reviewer

- [ ] Build it on your own local instance and test new features or changes.  
- [ ] Pass UITesting on your local instance on the matching UITesting branch.  
- [ ] It is functional and meets the requirements?   
- [ ] Are any shorthand variable names are included in the [Glossary](https://www.notion.so/rglab/Glossary-of-variable-abbreviations-e205838b1f534abc903fa8c2228a6d7f)?  
- [ ] Does it include descriptive code comments?   
- [ ] Does it follow the [Style Guide](https://github.com/RGLab/LabKeyModules/#style-guide) for any languages included?  
- [ ] Is it well-documented?
    * Module-specific README lists out any dependencies  
    * Sufficient instructions for setup  
    * Links to any relevant LabKey documentation   
- [ ] Are any new features tested via UITesting or jest?  
- [ ] Does it have any new dependencies? Is it justifiable?  
- [ ] Is there code duplication that could be reduced?  
- [ ] Are there performance improvements that could be made?

2021-04-23 20:57 UTC, juyeongkim reviewed
I will build and test on my local machine once these issues are addressed.

2021-04-23 20:57 UTC, juyeongkim commented on extraWebapp/build.gradle
> -    }
Restore the build script and replace these with your codes

2021-04-23 20:57 UTC, juyeongkim commented on extraWebapp/rstudio-viewer.html
> -<script type='text/javascript' src='js/ext-4.2.1/ext-all-sandbox.js'></script>
Restore this file and "deploy" (copy) this file into `${project.parent.deployDir}/extraWebapp` with `build.gradle` script. Or incorporate this in `/src`

2021-04-23 20:57 UTC, juyeongkim commented on .gitignore
> +node_modules
Delete the `build` directory and add it to `.gitignore`, so git won't be tracking and pushing them to GitHub.

2021-04-23 20:57 UTC, juyeongkim commented on extraWebapp/public/index.html
> +
- Include Google Analytics script: https://github.com/RGLab/LabKeyModules/blob/master/extraWebapp/index.html#L24-L34
- Update `favicon.ico` and the logo png files.

2021-04-23 21:04 UTC, juyeongkim commented on extraWebapp/build/manifest.json
> +  "name": "Create React App Sample",
Update these to "ImmuneSpace Entrance" and "Create ImmuneSpace Entrance Page"?

2021-04-23 21:54 UTC, guoz24 commented on extraWebapp/rstudio-viewer.html
> -<script type='text/javascript' src='js/ext-4.2.1/ext-all-sandbox.js'></script>
It's now in /public

2021-04-23 22:09 UTC, helenmiller16 requested changes
A few more comments! npm install failed on my local. At least part of it was based on not looking in the right place for @labkey/api. Make sure you change the React App defaults and remove the react logo, and use the new immunespace logo. Once I can build it on local, I'll go through and add any more notes.

2021-04-23 22:18 UTC, helenmiller16 commented
Can you also please include an overview of how it works and instructions for how to contribute in the README  in extraWebApp (and/or link to relevant Notion docs)

2021-04-26 23:09 UTC, helenmiller16 reviewed
Overall, everything is looking really good! Just trying to be somewhat consistent in code style. Make sure you're consistent in how you're declaring functions. And I noticed that you are passing in the full url to links, which I don't think should be necessary.

2021-04-26 23:09 UTC, helenmiller16 commented on extraWebapp/src/js/login.js
> +    url: `${homePageUrl}login/home/loginApi.api`,
Is there a reason you need to insert the homePageUrl and not just use relative links like here: https://github.com/RGLab/LabKeyModules/blob/master/DataFinder/src/client/DataFinder/components/Banner.tsx#L193
That seems simpler to me, although I think the best would be to use the LabKey ActionURL API.

2021-04-27 00:04 UTC, guoz24 commented on extraWebapp/src/js/login.js
> +    url: `${homePageUrl}login/home/loginApi.api`,
I did not think relative URLS would work for API calls but apparently it does? I've switched to relative.

2021-04-28 18:48 UTC, helenmiller16 approved these changes

2021-04-28 19:14 UTC, merged