Add Differential Expression module view
RGLab/LabKeyModules pull request #167
Opened 2022-01-07 00:32 UTC by helenmiller16

## Description

1. Create ETL to run differential expression 
2. Create view to display table with differential expression results (only available at individual studies level)

This removes all dependencies on UpdateAnno package from LabKeyModules

## Related PRs

https://github.com/RGLab/UITesting/pull/56

## Notion Ticket

https://www.notion.so/rglab/Differential-Expression-module-view-ade3f2fe65fe4a1fb08bc15e50f578be

## PR Checklist for reviewer

- [ ] Build it on your own local instance and test new features or changes.  
- [ ] Pass UITesting on your local instance on the matching UITesting branch.  
- [ ] It is functional and meets the requirements?   
- [ ] Are any shorthand variable names are included in the [Glossary](https://www.notion.so/rglab/Glossary-of-variable-abbreviations-e205838b1f534abc903fa8c2228a6d7f)?  
- [ ] Does it include descriptive code comments?   
- [ ] Does it follow the [Style Guide](https://github.com/RGLab/LabKeyModules/#style-guide) for any languages included?  
- [ ] Is it well-documented?
    * Module-specific README lists out any dependencies  
    * Sufficient instructions for setup  
    * Links to any relevant LabKey documentation   
- [ ] Are any new features tested via UITesting or jest?  
- [ ] Does it have any new dependencies? Is it justifiable?  
- [ ] Is there code duplication that could be reduced?  
- [ ] Are there performance improvements that could be made?

2022-01-07 00:51 UTC, juyeongkim commented
@helenmiller16 merge into `dev` please

2022-02-07 20:47 UTC, juyeongkim requested changes

2022-02-07 20:47 UTC, juyeongkim commented on ActiveModules/web/ActiveModules.js
> +                modules.pop();
Why pop twice?

2022-02-07 20:47 UTC, juyeongkim commented on DifferentialExpressionAnalysis/reports/schemas/DifferentialExpressionAnalysis.Rmd
>  library(DT)
DT is not being used anymore.

2022-02-07 20:47 UTC, juyeongkim commented on DifferentialExpressionAnalysis/reports/schemas/DifferentialExpressionAnalysis.report.xml
> +    <hidden>true</hidden>
👍

2022-02-07 20:47 UTC, juyeongkim commented on DifferentialExpressionAnalysis/views/begin.html
> +     </script>
Remove tab

2022-02-08 19:13 UTC, helenmiller16 commented on ActiveModules/web/ActiveModules.js
> +                modules.pop();
Remove both data explorer (It's under "analyze" tab instead) and Differential Expression (only meant to be viewed at study level at the moment).

2022-02-08 20:06 UTC, helenmiller16 commented on DifferentialExpressionAnalysis/reports/schemas/DifferentialExpressionAnalysis.Rmd
>  library(DT)
This report is not in use anymore so I deleted it. Module view is run from views/begin.html instead of R report. Which is more consistent with how React modules work with the frontend separate from R/data work.

2022-02-08 20:08 UTC, helenmiller16 commented
I deleted DifferentialExpressionAnalysis.Rmd because the module view is now controlled from view/begin.html, which is more consistent with how the React modules work, with frontend code separated from R/data-related code. Also updated the table in the view to use DGEA_filteredGEAR query, which filters out NA gene names

2022-02-08 21:30 UTC, juyeongkim approved these changes
Thanks for addressing my comments. It looks good. 💯

2022-03-09 00:44 UTC, merged